//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cous
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int CreditHour { get; set; }
        public string Type { get; set; }
    
        public virtual Cous Couses1 { get; set; }
        public virtual Cous Cous1 { get; set; }
    }
}
